package cloud.mone.hrm.aadhaar;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.charset.StandardCharsets;
import java.time.Instant;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * ⛔ SECURITY TEST. These vectors are shared with the Python service and were
 * verified byte-for-byte against it. If any of them change, the two sides no
 * longer agree and every request fails authentication in production — with no
 * other symptom.
 */
class AvsSignatureTest {

    private static final String KEY =
            "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

    @Test
    @DisplayName("★ matches the Python implementation exactly")
    void matchesPythonVectors() {
        // Generated by avs.security.build_signature and pinned here.
        assertEquals(
                "21af2d932e9050c7be1236ed8ce83198c030d5b500eabae99bfb87ae85ce56fd",
                AvsSignature.compute(KEY, "1755172800", "abc123",
                        "{\"a\":1}".getBytes(StandardCharsets.UTF_8)),
                "Java and Python disagree — authentication will fail everywhere");
    }

    @Test
    @DisplayName("⛔ the dot separators prevent a canonicalisation collision")
    void separatorsPreventCollision() {
        // Without delimiters ("12","3") and ("1","23") produce identical bytes,
        // letting an attacker shift characters between the two fields.
        String a = AvsSignature.compute(KEY, "12", "3", "x".getBytes(StandardCharsets.UTF_8));
        String b = AvsSignature.compute(KEY, "1", "23", "x".getBytes(StandardCharsets.UTF_8));
        assertNotEquals(a, b);
    }

    @Test
    @DisplayName("binary bodies sign correctly — a multipart body is not UTF-8")
    void signsBinaryBodies() {
        byte[] binary = {(byte) 0xFF, (byte) 0xD8, (byte) 0xFF, (byte) 0xE0, 0x00};
        assertEquals(64, AvsSignature.compute(KEY, "1", "n", binary).length());
    }

    @Test
    void acceptsAFreshSignature() {
        String ts = Long.toString(Instant.now().getEpochSecond());
        byte[] body = "{}".getBytes(StandardCharsets.UTF_8);
        String sig = AvsSignature.compute(KEY, ts, "n1", body);

        assertEquals(AvsSignature.Failure.OK, AvsSignature.verify(KEY, sig, ts, "n1", body));
    }

    @Test
    @DisplayName("⛔ a modified body is rejected")
    void rejectsModifiedBody() {
        String ts = Long.toString(Instant.now().getEpochSecond());
        String sig = AvsSignature.compute(KEY, ts, "n1", "{\"verdict\":\"TAMPERED\"}"
                .getBytes(StandardCharsets.UTF_8));

        assertEquals(
                AvsSignature.Failure.SIGNATURE_MISMATCH,
                AvsSignature.verify(KEY, sig, ts, "n1",
                        "{\"verdict\":\"VERIFIED\"}".getBytes(StandardCharsets.UTF_8)),
                "an attacker flipped the verdict and the signature still passed");
    }

    @Test
    @DisplayName("an expired timestamp is rejected")
    void rejectsStaleTimestamp() {
        String stale = Long.toString(Instant.now().getEpochSecond() - 3600);
        byte[] body = "{}".getBytes(StandardCharsets.UTF_8);

        assertEquals(
                AvsSignature.Failure.CLOCK_SKEW,
                AvsSignature.verify(KEY, AvsSignature.compute(KEY, stale, "n", body), stale, "n", body));
    }

    @Test
    @DisplayName("a future timestamp is also rejected — skew is absolute")
    void rejectsFutureTimestamp() {
        String future = Long.toString(Instant.now().getEpochSecond() + 3600);
        byte[] body = "{}".getBytes(StandardCharsets.UTF_8);

        assertEquals(
                AvsSignature.Failure.CLOCK_SKEW,
                AvsSignature.verify(KEY, AvsSignature.compute(KEY, future, "n", body), future, "n", body));
    }

    @Test
    void rejectsMissingHeaders() {
        assertEquals(
                AvsSignature.Failure.MISSING_HEADERS,
                AvsSignature.verify(KEY, null, null, null, new byte[0]));
    }
}
