#!/usr/bin/env python3
"""Build a complete, runnable demo of the Step 6 document verifier.

Produces a self-contained ``demo/`` directory: a signing key, a certificate, and
four card images covering the outcomes that matter.

    python scripts/make_demo_document.py

⛔ THE DEMO CERTIFICATE MUST NEVER GO IN ``certs/``

   ``demo/certs/`` holds a certificate for a key **we** generated. Anything signed
   with it will verify. That is exactly the trust-store poisoning attack the
   fingerprint pinning in Step 2 exists to prevent — a certificate in the trust
   store is a licence to mint approvals.

   So the demo keeps its own directory and every command below passes
   ``--certs demo/certs`` explicitly. The real ``certs/`` stays empty until you
   put a genuine UIDAI certificate in it.

   The private key is written to ``demo/`` too, purely so the script can rebuild
   the fixtures. ``demo/`` is git-ignored. Nothing here is a secret worth keeping
   — regenerate it whenever you like.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from tests.fixtures.certs import build_x509, write_certificate
from tests.fixtures.qr_images import encode_jpeg, render_card
from tests.fixtures.synthetic import SyntheticIdentity, SyntheticQrBuilder


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "demo")
    shutil.rmtree(root, ignore_errors=True)
    (root / "certs").mkdir(parents=True)

    print("=" * 70)
    print("AVS demo document builder")
    print("=" * 70)

    # ── A stand-in signing authority ─────────────────────────────────────
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    certificate = build_x509(key, common_name="DEMO KEY - NOT UIDAI - DO NOT TRUST")
    write_certificate(certificate, root / "certs" / "demo-signing-key.pem")
    (root / "demo-signing-key.key").write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    (root / "certs" / "README.txt").write_text(
        "This certificate belongs to a key generated by make_demo_document.py.\n"
        "Anything signed with it verifies. NEVER copy it into the real certs/\n"
        "directory — a certificate in the trust store is a licence to mint\n"
        "approvals, which is precisely what Step 2's pinning prevents.\n",
        encoding="utf-8",
    )

    # ── The document ─────────────────────────────────────────────────────
    builder = SyntheticQrBuilder(private_key=key)
    genuine = builder.build()

    files: list[tuple[str, bytes, str]] = [
        (
            "front.jpg",
            encode_jpeg(render_card("https://example.com/front-face-has-no-secure-qr")),
            "front face — no Secure QR (normal for a PVC card)",
        ),
        (
            "back.jpg",
            encode_jpeg(render_card(genuine)),
            "back face — genuine signed Secure QR",
        ),
        (
            "back_tampered.jpg",
            encode_jpeg(
                render_card(builder.build_tampered(field_name="name", new_value="Someone Else"))
            ),
            "back face — name edited, signature reused",
        ),
        (
            "back_other_card.jpg",
            encode_jpeg(
                render_card(
                    SyntheticQrBuilder(
                        private_key=key,
                        identity=SyntheticIdentity(
                            reference_id="9876202608131030000", name="Different Person"
                        ),
                    ).build()
                )
            ),
            "back face — a DIFFERENT person's genuine card",
        ),
    ]

    print(f"\nWriting to {root.resolve()}\n")
    for name, data, description in files:
        (root / name).write_bytes(data)
        print(f"  {name:<22} {len(data):>9,} bytes   {description}")

    sep = "\\" if sys.platform == "win32" else "/"
    d = str(root)

    print("\n" + "=" * 70)
    print("TRY THESE")
    print("=" * 70)
    for label, front, back, expected in [
        ("Genuine document", "front.jpg", "back.jpg", "VERIFIED"),
        ("Name edited on the back", "front.jpg", "back_tampered.jpg", "TAMPERED"),
        (
            "Two faces from different cards",
            "back.jpg",
            "back_other_card.jpg",
            "TEXT_MISMATCH -> HR review",
        ),
        ("QR on the FRONT instead", "back.jpg", "front.jpg", "VERIFIED"),
    ]:
        print(f"\n  # {label}  ->  expect {expected}")
        print(f"  avs verify {d}{sep}{front} {d}{sep}{back} --certs {d}{sep}certs")

    print("\n  # Add --show-fields to any of the above to see the signed data.")
    print("\n" + "=" * 70)
    print("The last one is the important one: the Secure QR may be on EITHER")
    print("side. A system that assumed 'QR = back' would fail for a large share")
    print("of genuine cards.")
    print("=" * 70)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
